### Create new user
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "first_name": "Micheal",
    "last_name": "Myers",
    "username": "mmyers983",
    "email": "mm@test.com",
    "password": "D32dndktuyios"
}

### Login User
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "mm@test.com",
  "password": "D32dndktuyios"
}

###
GET http://localhost:8000/api/v1/auth/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoibW1AdGVzdC5jb20iLCJ1c2VyX3VpZCI6ImY3NTlmOGMzLTljMWMtNDk5MC05MWVmLWU0ODViNmVkODg2ZCJ9LCJleHAiOjE3NDMxOTU2MDcsImp0aSI6IjJjNjM1Y2ZiLTE2YWYtNGE5OS05M2FkLWEyMTlmYTJiNTAwMyIsInJlZnJlc2giOnRydWV9.5UZBfi31NGTuHfDg2AUDf7vbD9ngIx1vg1yMExnCF0Q

###
GET http://localhost:8000/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoibW1AdGVzdC5jb20iLCJ1c2VyX3VpZCI6ImY3NTlmOGMzLTljMWMtNDk5MC05MWVmLWU0ODViNmVkODg2ZCJ9LCJleHAiOjE3NDMwMjcxNzksImp0aSI6IjhkZDEyODI1LTFlNmEtNDMwMC1hOTAxLWRkM2E3YWIxMTljYSIsInJlZnJlc2giOmZhbHNlfQ.68qtu7YTaWfEAtFHTYxNiwOXcxvkPPJSCnOE6EKNOh8

###
GET http://localhost:8000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoibW1AdGVzdC5jb20iLCJ1c2VyX3VpZCI6IjYzOGRhM2NhLTFiOGItNGQ1NC04ZDYxLWZhNzFjMmU5NDZmYiIsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTc0NDQwNzE1MiwianRpIjoiZmM4OTg5ZjMtMWYxNy00YmI5LThkNmItMjgwM2NmMmViMGUyIiwicmVmcmVzaCI6ZmFsc2V9.JxQU4IF7EPuRGeB80crOR9OzpZqjzafoiBZb2fbj5t8